---
title: MoMA
author: Adam Filipowicz
date: '2020-04-08'
slug: moma
categories: []
tags:
  - Data Visualization
summary: 'We take a look at the MoMA Collection Dataset, recreating a number of interesting graphs.'
authors: []
external_link: ''
image: 
  placement: 1
  caption: ''
  focal_point: 'Smart'
  preview_only: no
url_code: ''
url_pdf: ''
url_slides: ''
url_video: ''
slides: ''
output:
  html_document:
    theme: flatly
    toc: TRUE
    toc_float: TRUE
    toc_depth: 2
    number_sections: TRUE
    code_folding: hide
---



<div id="workflow-for-lab-02" class="section level1">
<h1>Workflow for Lab 02</h1>
<p>The lab instructions can be found <a href="https://stevenbedrick.github.io/data-vis-labs-2020/02-moma.html">here</a>; we will work through its contents together via Webex. You will use this RMarkdown file as your workspace and final document. Don’t forget to update the “author” metadata field at the top of the file!</p>
</div>
<div id="start-by-loading-libraries" class="section level1">
<h1>Start by Loading Libraries</h1>
<p>Load packages readr, here, tidyverse, and ggthemes</p>
<pre class="r"><code>library(readr)
library(here)</code></pre>
<pre><code>## here() starts at C:/Users/flip7/Documents/GitHub/academic-kickstart</code></pre>
<pre class="r"><code>library(tidyverse)</code></pre>
<pre><code>## -- Attaching packages ------------------------------------------------------------------------------------------- tidyverse 1.3.0 --</code></pre>
<pre><code>## v ggplot2 3.3.0     v dplyr   0.8.5
## v tibble  3.0.1     v stringr 1.4.0
## v tidyr   1.0.2     v forcats 0.5.0
## v purrr   0.3.3</code></pre>
<pre><code>## -- Conflicts ---------------------------------------------------------------------------------------------- tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>library(ggthemes)
library(extrafont)</code></pre>
<pre><code>## Registering fonts with R</code></pre>
<p>We’re going to read in the cleaned up data set containing only paintings and drawings in the MoMA collection:</p>
<pre class="r"><code>library(dplyr)
moma &lt;- read_csv(here::here(&quot;artworks-cleaned.csv&quot;))</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   .default = col_double(),
##   title = col_character(),
##   artist = col_character(),
##   artist_bio = col_character(),
##   artist_gender = col_character(),
##   circumference_cm = col_logical(),
##   diameter_cm = col_logical(),
##   length_cm = col_logical(),
##   seat_height_cm = col_logical(),
##   purchase = col_logical(),
##   gift = col_logical(),
##   exchange = col_logical(),
##   classification = col_character(),
##   department = col_character()
## )</code></pre>
<pre><code>## See spec(...) for full column specifications.</code></pre>
</div>
<div id="know-your-data" class="section level1">
<h1>Know Your Data</h1>
<p>Let’s use dplyr to get to know our data.</p>
<div id="how-many-paintings" class="section level2">
<h2>How Many Paintings?</h2>
<pre class="r"><code>moma</code></pre>
<pre><code>## # A tibble: 2,253 x 23
##    title artist artist_bio artist_birth_ye~ artist_death_ye~ num_artists
##    &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;                 &lt;dbl&gt;            &lt;dbl&gt;       &lt;dbl&gt;
##  1 &quot;Rop~ Joan ~ (Spanish,~             1893             1983           1
##  2 &quot;Fir~ Paul ~ (German, ~             1879             1940           1
##  3 &quot;Por~ Paul ~ (German, ~             1879             1940           1
##  4 &quot;Gui~ Pablo~ (Spanish,~             1881             1973           1
##  5 &quot;Gra~ Arthu~ (American~             1880             1946           1
##  6 &quot;\&quot;M~ Franc~ (French, ~             1879             1953           1
##  7 &quot;Unt~ Blink~ (German, ~             1943             1977           1
##  8 &quot;Day~ Pierr~ (French, ~             1880             1950           1
##  9 &quot;The~ Paul ~ (French, ~             1839             1906           1
## 10 &quot;Syn~ Enric~ (Italian,~             1894             1956           1
## # ... with 2,243 more rows, and 17 more variables: n_female_artists &lt;dbl&gt;,
## #   n_male_artists &lt;dbl&gt;, artist_gender &lt;chr&gt;, year_acquired &lt;dbl&gt;,
## #   year_created &lt;dbl&gt;, circumference_cm &lt;lgl&gt;, depth_cm &lt;dbl&gt;,
## #   diameter_cm &lt;lgl&gt;, height_cm &lt;dbl&gt;, length_cm &lt;lgl&gt;, width_cm &lt;dbl&gt;,
## #   seat_height_cm &lt;lgl&gt;, purchase &lt;lgl&gt;, gift &lt;lgl&gt;, exchange &lt;lgl&gt;,
## #   classification &lt;chr&gt;, department &lt;chr&gt;</code></pre>
<pre class="r"><code>glimpse(moma)</code></pre>
<pre><code>## Rows: 2,253
## Columns: 23
## $ title             &lt;chr&gt; &quot;Rope and People, I&quot;, &quot;Fire in the Evening&quot;, &quot;Por...
## $ artist            &lt;chr&gt; &quot;Joan Miró&quot;, &quot;Paul Klee&quot;, &quot;Paul Klee&quot;, &quot;Pablo Pic...
## $ artist_bio        &lt;chr&gt; &quot;(Spanish, 1893–1983)&quot;, &quot;(German, born Switzerlan...
## $ artist_birth_year &lt;dbl&gt; 1893, 1879, 1879, 1881, 1880, 1879, 1943, 1880, 1...
## $ artist_death_year &lt;dbl&gt; 1983, 1940, 1940, 1973, 1946, 1953, 1977, 1950, 1...
## $ num_artists       &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1...
## $ n_female_artists  &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...
## $ n_male_artists    &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1...
## $ artist_gender     &lt;chr&gt; &quot;Male&quot;, &quot;Male&quot;, &quot;Male&quot;, &quot;Male&quot;, &quot;Male&quot;, &quot;Male&quot;, &quot;...
## $ year_acquired     &lt;dbl&gt; 1936, 1970, 1966, 1955, 1939, 1968, 1997, 1931, 1...
## $ year_created      &lt;dbl&gt; 1935, 1929, 1927, 1919, 1925, 1919, 1970, 1929, 1...
## $ circumference_cm  &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N...
## $ depth_cm          &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N...
## $ diameter_cm       &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N...
## $ height_cm         &lt;dbl&gt; 104.8, 33.8, 60.3, 215.9, 50.8, 129.2, 200.0, 54....
## $ length_cm         &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N...
## $ width_cm          &lt;dbl&gt; 74.6, 33.3, 36.8, 78.7, 54.0, 89.9, 200.0, 38.1, ...
## $ seat_height_cm    &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N...
## $ purchase          &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, ...
## $ gift              &lt;lgl&gt; TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, TRUE, TRUE...
## $ exchange          &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, F...
## $ classification    &lt;chr&gt; &quot;Painting&quot;, &quot;Painting&quot;, &quot;Painting&quot;, &quot;Painting&quot;, &quot;...
## $ department        &lt;chr&gt; &quot;Painting &amp; Sculpture&quot;, &quot;Painting &amp; Sculpture&quot;, &quot;...</code></pre>
<p>Looks like 2,253 paintings (rows) and 23 variables (columns) are in moma.</p>
</div>
<div id="what-is-the-first-painting-that-was-acquired" class="section level2">
<h2>What is the first painting that was acquired?</h2>
<pre class="r"><code>moma %&gt;% 
  select(artist, title, year_acquired) %&gt;% 
  arrange(year_acquired)</code></pre>
<pre><code>## # A tibble: 2,253 x 3
##    artist           title                                          year_acquired
##    &lt;chr&gt;            &lt;chr&gt;                                                  &lt;dbl&gt;
##  1 Edward Hopper    House by the Railroad                                   1930
##  2 Bernard Karfiol  Seated Nude                                             1930
##  3 Pierre Roy       Daylight Savings Time                                   1931
##  4 Preston Dickins~ Plums on a Plate                                        1931
##  5 Otto Dix         Dr. Mayer-Hermann                                       1932
##  6 Paul Cézanne     The Bather                                              1934
##  7 Paul Cézanne     Pines and Rocks (Fontainebleau?)                        1934
##  8 Paul Cézanne     Still Life with Ginger Jar, Sugar Bowl, and O~          1934
##  9 Paul Cézanne     Still Life with Apples                                  1934
## 10 Arthur B. Davies Italian Landscape                                       1934
## # ... with 2,243 more rows</code></pre>
<p>The first paining acquired was “House by the Railroad” by Edward Hopper in 1930.</p>
</div>
<div id="what-is-the-oldest-painting" class="section level2">
<h2>What is the oldest painting?</h2>
<pre class="r"><code>moma %&gt;% 
  select(artist, title, year_created) %&gt;% 
  arrange(year_created)</code></pre>
<pre><code>## # A tibble: 2,253 x 3
##    artist       title                                    year_created
##    &lt;chr&gt;        &lt;chr&gt;                                           &lt;dbl&gt;
##  1 Odilon Redon Landscape at Daybreak                            1872
##  2 Odilon Redon Apache (Man on Horseback)                        1875
##  3 Odilon Redon Apache (Man on Horseback II)                     1875
##  4 Odilon Redon Fishing Boat                                     1875
##  5 Odilon Redon Rocky Peak                                       1875
##  6 Odilon Redon The Rocky Slope                                  1875
##  7 Odilon Redon Landscape with Rocks, near Royan                 1875
##  8 Paul Cézanne Still Life with Fruit Dish                       1879
##  9 Paul Cézanne L&#39;Estaque                                        1879
## 10 Claude Monet On the Cliff at Pourville, Clear Weather         1882
## # ... with 2,243 more rows</code></pre>
<p>The oldest painting, “Landscape at Daybreak” by Odilon Redon, is from 1872.</p>
</div>
<div id="how-many-artists" class="section level2">
<h2>How many artists?</h2>
<pre class="r"><code>moma %&gt;% 
  distinct(artist)</code></pre>
<pre><code>## # A tibble: 989 x 1
##    artist           
##    &lt;chr&gt;            
##  1 Joan Miró        
##  2 Paul Klee        
##  3 Pablo Picasso    
##  4 Arthur Dove      
##  5 Francis Picabia  
##  6 Blinky Palermo   
##  7 Pierre Roy       
##  8 Paul Cézanne     
##  9 Enrico Prampolini
## 10 Jankel Adler     
## # ... with 979 more rows</code></pre>
<p>989 rows there, so there are 989 distinct artists.</p>
</div>
<div id="which-artist-has-the-most-paintings" class="section level2">
<h2>Which artist has the most paintings?</h2>
<pre class="r"><code>moma %&gt;% 
  count(artist, sort = TRUE)</code></pre>
<pre><code>## # A tibble: 989 x 2
##    artist               n
##    &lt;chr&gt;            &lt;int&gt;
##  1 Pablo Picasso       55
##  2 Henri Matisse       32
##  3 On Kawara           32
##  4 Jacob Lawrence      30
##  5 Batiste Madalena    25
##  6 Jean Dubuffet       25
##  7 Odilon Redon        25
##  8 Ben Vautier         24
##  9 Frank Stella        23
## 10 Philip Guston       23
## # ... with 979 more rows</code></pre>
<p>Pablo Picasso has the most paintings, at 55 total paintings.</p>
</div>
<div id="how-many-paintings-by-gender" class="section level2">
<h2>How many paintings, by gender?</h2>
<pre class="r"><code>moma %&gt;% 
  count(artist_gender)</code></pre>
<pre><code>## # A tibble: 3 x 2
##   artist_gender     n
##   &lt;chr&gt;         &lt;int&gt;
## 1 Female          252
## 2 Male           1991
## 3 &lt;NA&gt;             10</code></pre>
<p>So 252 paintings by females, and 1991 by males, and 10 paintings with no information available.</p>
</div>
<div id="how-many-artists-by-gender" class="section level2">
<h2>How many artists, by gender?</h2>
<pre class="r"><code>moma %&gt;% 
  count(artist_gender, artist) %&gt;% 
  count(artist_gender)</code></pre>
<pre><code>## # A tibble: 3 x 2
##   artist_gender     n
##   &lt;chr&gt;         &lt;int&gt;
## 1 Female          143
## 2 Male            837
## 3 &lt;NA&gt;              9</code></pre>
<p>By using count twice, we can pull out how many unique artists there are per gender: 143 females, 837 males, and 9 N/A.</p>
</div>
<div id="in-which-years-were-the-most-paintings-in-the-collection-acquired" class="section level2">
<h2>In which years were the most paintings in the collection <em>acquired</em>?</h2>
<pre class="r"><code>moma %&gt;% 
  count(year_acquired, sort = TRUE)</code></pre>
<pre><code>## # A tibble: 88 x 2
##    year_acquired     n
##            &lt;dbl&gt; &lt;int&gt;
##  1          1985    86
##  2          1942    71
##  3          1979    71
##  4          1991    67
##  5          2005    67
##  6          1967    65
##  7          2008    55
##  8          1961    45
##  9          1969    45
## 10          1956    42
## # ... with 78 more rows</code></pre>
<p>1985 saw the most paintings acquired, at 86 paintings.</p>
</div>
<div id="in-which-years-were-the-most-paintings-in-the-collection-created" class="section level2">
<h2>In which years were the most paintings in the collection <em>created</em>?</h2>
<pre class="r"><code>moma %&gt;% 
  count(year_created, sort = TRUE)</code></pre>
<pre><code>## # A tibble: 139 x 2
##    year_created     n
##           &lt;dbl&gt; &lt;int&gt;
##  1         1977    57
##  2         1940    56
##  3         1964    56
##  4         1961    50
##  5         1962    49
##  6         1963    44
##  7         1959    42
##  8         1968    40
##  9         1960    39
## 10         1914    37
## # ... with 129 more rows</code></pre>
<p>The most common year of creation for paintings in the collection was 1977, with 57 of the paintings created in that year.</p>
</div>
<div id="what-about-the-first-painting-by-a-solo-female-artist" class="section level2">
<h2>What about the first painting by a solo female artist?</h2>
<pre class="r"><code>moma %&gt;% 
  filter (num_artists == 1 &amp; n_female_artists == 1) %&gt;%
  select(title, artist, year_acquired, year_created) %&gt;% 
  arrange(year_acquired)</code></pre>
<pre><code>## # A tibble: 252 x 4
##    title                        artist                year_acquired year_created
##    &lt;chr&gt;                        &lt;chr&gt;                         &lt;dbl&gt;        &lt;dbl&gt;
##  1 Landscape, 47                Natalia Goncharova             1937         1912
##  2 Shack                        Loren MacIver                  1938         1934
##  3 Hopscotch                    Loren MacIver                  1940         1940
##  4 Shadows with Painting        Irene Rice Pereira             1941         1940
##  5 Figure                       Varvara Stepanova              1941         1921
##  6 Still Life in Red            Amelia Peláez Del Ca~          1942         1938
##  7 White Lines                  Irene Rice Pereira             1942         1942
##  8 Musical Squash               Maud Morgan                    1942         1942
##  9 Desolation                   Raquel Forner                  1942         1942
## 10 Self-Portrait with Cropped ~ Frida Kahlo                    1943         1940
## # ... with 242 more rows</code></pre>
<p>“Landscape, 47” created by Natalia Goncharova in 1912, was the first painting by a solo female artist acquired, added to the collection in 1937.</p>
</div>
</div>
<div id="basic-plotting" class="section level1">
<h1>Basic Plotting!</h1>
<div id="year-painted-vs.-year-acquired" class="section level2">
<h2>Year painted vs. year acquired</h2>
<pre class="r"><code>ggplot(moma, aes(year_created, year_acquired)) + 
  geom_point(alpha = .1, na.rm = TRUE) +
  geom_abline(intercept = c(0,0), colour = &quot;red&quot;) +
  labs(x = &quot;Year Painted&quot;, y = &quot;Year Acquired&quot;) +
  ggtitle(&quot;MoMA Keeps Its Collection Current&quot;)</code></pre>
<p><img src="/project/2020-04-08-moma/index_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
</div>
<div id="faceting-by-gender" class="section level2">
<h2>Faceting by gender</h2>
<pre class="r"><code>moma_solo &lt;- moma %&gt;% 
  filter(num_artists == 1)
ggplot(moma_solo, aes(year_created, year_acquired)) +
  geom_point(alpha = .1) +
  geom_abline(intercept = c(0,0), colour = &quot;red&quot;) +
  labs(x = &quot;Year Painted&quot;, y = &quot;Year Acquired&quot;) +
  ggtitle(&quot;MoMA Keeps Its Collection Current&quot;) +
  facet_wrap(~artist_gender)</code></pre>
<pre><code>## Warning: Removed 14 rows containing missing values (geom_point).</code></pre>
<p><img src="/project/2020-04-08-moma/index_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
</div>
</div>
<div id="exploring-painting-dimensions" class="section level1">
<h1>Exploring Painting Dimensions</h1>
<pre class="r"><code>moma_dim &lt;- moma %&gt;% 
  filter(height_cm &lt; 600, width_cm &lt; 760) %&gt;% 
  mutate(hw_ratio = height_cm / width_cm,
         hw_cat = case_when(
           hw_ratio &gt; 1 ~ &quot;taller than wide&quot;,
           hw_ratio &lt; 1 ~ &quot;wider than tall&quot;,
           hw_ratio == 1 ~ &quot;perfect square&quot;
         ))
library(ggthemes)
ggplot(moma_dim, aes(x = width_cm, y = height_cm, colour = hw_cat)) +
  geom_point(alpha = .5) +
  ggtitle(&quot;MoMA Paintings, Tall and Wide&quot;) +
  scale_colour_manual(name = &quot;&quot;,
                      values = c(&quot;gray50&quot;, &quot;#FF9900&quot;, &quot;#B14CF0&quot;)) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) +
  labs(x = &quot;Width&quot;, y = &quot;Height&quot;)</code></pre>
<p><img src="/project/2020-04-08-moma/index_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<div id="challenge-4" class="section level2">
<h2>Challenge #4</h2>
</div>
<div id="different-colors" class="section level2">
<h2>Different colors</h2>
<pre class="r"><code>library(ggthemes)
ggplot(moma_dim, aes(x = width_cm, y = height_cm, colour = hw_cat)) +
  geom_point(alpha = .5) +
  ggtitle(&quot;MoMA Paintings, Tall and Wide&quot;) +
  scale_colour_manual(name = &quot;&quot;,
                      values = c(&quot;gray50&quot;, &quot;#ee5863&quot;, &quot;#6999cd&quot;)) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) +
  labs(x = &quot;Width&quot;, y = &quot;Height&quot;) </code></pre>
<p><img src="/project/2020-04-08-moma/index_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
</div>
<div id="experimenting-with-geom_annotate" class="section level2">
<h2>Experimenting with <code>geom_annotate()</code></h2>
<pre class="r"><code>library(ggthemes)
ggplot(moma_dim, aes(x = width_cm, y = height_cm, colour = hw_cat)) +
  geom_point(alpha = .5, show.legend = FALSE) +
  ggtitle(&quot;MoMA Paintings, Tall and Wide&quot;) +
  scale_colour_manual(name = &quot;&quot;,
                      values = c(&quot;gray50&quot;, &quot;#ee5863&quot;, &quot;#6999cd&quot;)) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) +
  labs(x = &quot;Width&quot;, y = &quot;Height&quot;) +
  annotate(x = 200, y = 380, geom = &quot;text&quot;, 
           label = &quot;Taller than\nWide&quot;, color = &quot;#ee5863&quot;, 
           size = 5, family = &quot;Lato&quot;, hjust = 1, fontface = 2) +
    annotate(x = 375, y = 100, geom = &quot;text&quot;, 
             label = &quot;Wider than\nTall&quot;, color = &quot;#6999cd&quot;, 
             size = 5, family = &quot;Lato&quot;, hjust = 0, fontface = 2)</code></pre>
<p><img src="/project/2020-04-08-moma/index_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
</div>
</div>
<div id="challenge-5-on-your-own" class="section level1">
<h1>Challenge #5, on your own!</h1>
<p>I want to delve into the gender distribution of the MoMA collection a bit further. The graph by Twitter user <span class="citation">@EamonCaddigan</span> served as inspiration: <a href="https://twitter.com/EamonCaddigan/status/626861365546848256" class="uri">https://twitter.com/EamonCaddigan/status/626861365546848256</a>. First, let’s switch the ordering of the “Male” and “Female” groups using forcats. This is just for aesthetic purposes later. We’ll also take a look at the mean for each group in terms of “Year Acquired”</p>
<pre class="r"><code>library(forcats)
moma_solo_relevel &lt;- moma_solo %&gt;% 
  mutate(artist_gender = fct_relevel(artist_gender, &quot;Male&quot;, &quot;Female&quot;))

mu &lt;- moma_solo_relevel %&gt;% 
  group_by(artist_gender) %&gt;%  
  summarize(grp.mean=mean(year_acquired, na.rm = TRUE))
head(mu)</code></pre>
<pre><code>## # A tibble: 2 x 2
##   artist_gender grp.mean
##   &lt;fct&gt;            &lt;dbl&gt;
## 1 Male             1974.
## 2 Female           1989.</code></pre>
<p>Looks like the average acquisition year for paintings by male artists was 1973, while the average for female artists was 1988. With this information, we can already suspect that in the early years the collection skewed heavily toward male artists while in more recent years an effort has been made to acquire more work by female artists. Let’s make an attempt at graphing this to get a better sense of what the trend is. I’m going to use a bar chart to give me the counts for each year of acquisition, and break them up by gender.</p>
<pre class="r"><code>ggplot(moma_solo_relevel, aes(x=year_acquired, fill=artist_gender, color=artist_gender)) +
  geom_bar(alpha = 0.7, position = &quot;stack&quot;, show.legend = FALSE) +
  geom_vline(data=mu, aes(xintercept=grp.mean, color=artist_gender),
             linetype=&quot;dashed&quot;, show.legend = FALSE) +
  theme_fivethirtyeight() +
  scale_colour_manual(values = c(&quot;#63ACBE&quot;, &quot;#EE442F&quot;)) +
  scale_fill_manual(values = c(&quot;#63ACBE&quot;, &quot;#EE442F&quot;)) +
  theme(axis.title = element_text()) +
  labs(x = &quot;Year Acquired&quot;, y = &quot;Count&quot;) +
  ggtitle(&quot;Gender Distribution of the MoMA Collection&quot;) +
  annotate(x = 1973, y = 75, geom = &quot;text&quot;, 
           label = &quot;Average-&gt;\nMales    &quot;, color = &quot;#63ACBE&quot;, 
           size = 5, family = &quot;Lato&quot;, hjust = 1, fontface = 3) +
    annotate(x = 1989, y = 75, geom = &quot;text&quot;, 
             label = &quot;&lt;-Average\n    Females&quot;, color = &quot;#EE442F&quot;, 
             size = 5, family = &quot;Lato&quot;, hjust = 0, fontface = 3)</code></pre>
<pre><code>## Warning: Removed 9 rows containing non-finite values (stat_count).</code></pre>
<p><img src="/project/2020-04-08-moma/index_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>By raw counts we can clearly see that overall the collection skews heavily male, though, as we suspected, in recent years more of an effort has gone into acquiring work by female artists.</p>
<p>Another way to represent this would be to use a density plot:</p>
<pre class="r"><code>ggplot(moma_solo_relevel, aes(x=year_acquired, color=artist_gender, fill=artist_gender)) +
  geom_density(alpha = 0.7, show.legend = FALSE) +
  geom_vline(data=mu, aes(xintercept=grp.mean, color=artist_gender),
             linetype=&quot;dashed&quot;, show.legend = FALSE) +
  theme_fivethirtyeight() +
  scale_colour_manual(values = c(&quot;#63ACBE&quot;, &quot;#EE442F&quot;)) +
  scale_fill_manual(values = c(&quot;#63ACBE&quot;, &quot;#EE442F&quot;)) +
  theme(axis.title = element_text()) +
  labs(x = &quot;Year Acquired&quot;, y = &quot;Density&quot;) +
  ggtitle(&quot;Gender Distribution of the MoMA Collection&quot;) + 
  annotate(x = 1973, y = .02, geom = &quot;text&quot;, 
           label = &quot;Average-&gt;\nMales    &quot;, color = &quot;#63ACBE&quot;, 
           size = 5, family = &quot;Lato&quot;, hjust = 1, fontface = 3) +
  annotate(x = 1989, y = .02, geom = &quot;text&quot;, 
             label = &quot;&lt;-Average\n    Females&quot;, color = &quot;#EE442F&quot;, 
             size = 5, family = &quot;Lato&quot;, hjust = 0, fontface = 3)</code></pre>
<pre><code>## Warning: Removed 9 rows containing non-finite values (stat_density).</code></pre>
<p><img src="/project/2020-04-08-moma/index_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>This graph makes even more clear that the collection has started to acquire more paintings by females in recent years, with it being quite low at the earliest time points in this data set. Acquisitions of paintings by males has remained pretty steady throughout the time period analyzed here. The drop off for both groups at the right edge of the graph represents the fact that it usually takes the MoMA some years to add pieces to their collection. We looked at one way of representing this above, but with just some simple math I think we could make it look better (and also fit it to a generalized additive model to see the trend more clearly). Another Twitter user, had the same idea, though I don’t know how the trend-line was produced: <a href="https://twitter.com/freakonometrics/status/626274944293449728" class="uri">https://twitter.com/freakonometrics/status/626274944293449728</a>.</p>
<pre class="r"><code>ggplot(moma, aes(year_acquired, year_acquired-year_created)) + 
  geom_point(alpha = .1, na.rm = TRUE) +
  geom_smooth(se=FALSE, color = &quot;#EE442F&quot;) +
  theme_tufte() +
  labs(x = &quot;Year Acquired&quot;, y = &quot;Age (years) at time of acquisition&quot;) +
  ggtitle(&quot;MoMA Keeps Things Fresh&quot;)</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;gam&#39; and formula &#39;y ~ s(x, bs = &quot;cs&quot;)&#39;</code></pre>
<pre><code>## Warning: Removed 14 rows containing non-finite values (stat_smooth).</code></pre>
<p><img src="/project/2020-04-08-moma/index_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>This is pretty much the same as the first graph we made up above, but shifted so that the identity line (y=x) is now just the x-axis. The trend-line is based on a GAM, which makes clear that there is usually a bit of lag between the creation of a painting and it being acquired by the MoMA, with the lag time showing a slight increase over the years.</p>
</div>
